import { JobSearchCriteria, NormalizedJob } from "./types";

export function getFallbackJobs(criteria: JobSearchCriteria): NormalizedJob[] {
  const role = criteria.jobTitles?.[0] || "Software Engineer";
  const loc = criteria.location || "Bengaluru / Remote";

  return [
    {
      source: "LinkedIn Jobs",
      sourceJobId: "fb-1",
      title: `${role} - Core Platform`,
      company: "Razorpay",
      location: loc,
      remoteType: "Hybrid",
      experienceMin: 1,
      experienceMax: 4,
      salaryMin: 1400000,
      salaryMax: 2400000,
      employmentType: "Full-time",
      skills: criteria.skills?.slice(0, 5) || ["React", "TypeScript", "Node.js", "PostgreSQL"],
      description: `We are looking for a passionate ${role} to join our high-growth platform team. You will build and scale high-availability systems with cutting-edge tech stack.`,
      applicationUrl: "https://www.linkedin.com/jobs",
      postedAt: new Date(),
    },
    {
      source: "Indeed",
      sourceJobId: "fb-2",
      title: `Senior ${role}`,
      company: "Swiggy",
      location: loc,
      remoteType: "Remote",
      experienceMin: 2,
      experienceMax: 5,
      salaryMin: 1800000,
      salaryMax: 3000000,
      employmentType: "Full-time",
      skills: criteria.skills?.slice(0, 4) || ["JavaScript", "React", "Next.js", "Tailwind CSS"],
      description: `Join Swiggy's consumer tech team to deliver blazing fast user experiences to tens of millions of active users daily.`,
      applicationUrl: "https://in.indeed.com",
      postedAt: new Date(),
    },
    {
      source: "Instahyre",
      sourceJobId: "fb-3",
      title: `${role}`,
      company: "CRED",
      location: loc,
      remoteType: "Hybrid",
      experienceMin: 0,
      experienceMax: 3,
      salaryMin: 1600000,
      salaryMax: 2800000,
      employmentType: "Full-time",
      skills: criteria.skills?.slice(0, 4) || ["TypeScript", "Next.js", "Docker", "AWS"],
      description: `Design and develop fluid, aesthetic and high-performance financial systems that delight top-tier users across the country.`,
      applicationUrl: "https://www.instahyre.com",
      postedAt: new Date(),
    },
    {
      source: "LinkedIn Jobs",
      sourceJobId: "fb-4",
      title: `${role} (Product Engineering)`,
      company: "Zomato",
      location: loc,
      remoteType: "On-site",
      experienceMin: 1,
      experienceMax: 3,
      salaryMin: 1200000,
      salaryMax: 2200000,
      employmentType: "Full-time",
      skills: criteria.skills?.slice(0, 5) || ["React", "Python", "SQL", "Git"],
      description: `Work closely with design and product teams to architect scalable front-end and full-stack solutions with great attention to detail.`,
      applicationUrl: "https://www.linkedin.com/jobs",
      postedAt: new Date(),
    },
    {
      source: "SimplyHired",
      sourceJobId: "fb-5",
      title: `Associate ${role}`,
      company: "PhonePe",
      location: loc,
      remoteType: "Hybrid",
      experienceMin: 0,
      experienceMax: 2,
      salaryMin: 1200000,
      salaryMax: 1800000,
      employmentType: "Full-time",
      skills: criteria.skills?.slice(0, 4) || ["JavaScript", "HTML5", "CSS3", "REST APIs"],
      description: `Fast-track your career in fintech. Solve complex algorithmic challenges and contribute to payments infrastructure processing billions of transactions.`,
      applicationUrl: "https://www.simplyhired.co.in",
      postedAt: new Date(),
    },
    {
      source: "Internshala",
      sourceJobId: "fb-6",
      title: `${role} Trainee / Junior`,
      company: "Freshworks",
      location: loc,
      remoteType: "Remote",
      experienceMin: 0,
      experienceMax: 2,
      salaryMin: 800000,
      salaryMax: 1500000,
      employmentType: "Full-time",
      skills: criteria.skills?.slice(0, 4) || ["React", "Node.js", "Problem Solving"],
      description: `Exciting opportunity for rising engineers to learn best engineering practices and ship customer-facing features directly.`,
      applicationUrl: "https://internshala.com",
      postedAt: new Date(),
    },
  ];
}
