import { JobSearchCriteria, NormalizedJob } from "./types";

export function getFallbackJobs(criteria: JobSearchCriteria): NormalizedJob[] {
  const role = criteria.jobTitles?.[0] || "UI/UX Designer";
  const loc = criteria.location || "Hyderabad / Remote";
  const isFresher = criteria.experience === 0 || (criteria.experience !== undefined && criteria.experience <= 1);

  if (role.toLowerCase().includes("design") || role.toLowerCase().includes("ui") || role.toLowerCase().includes("ux")) {
    return [
      {
        source: "Foundit",
        sourceJobId: "cur-des-1",
        title: isFresher ? "Junior UI/UX Designer" : "UI/UX Designer",
        company: "Razorpay",
        location: loc,
        remoteType: "Hybrid",
        experienceMin: 0,
        experienceMax: isFresher ? 1 : 3,
        salaryMin: 800000,
        salaryMax: 1500000,
        employmentType: "Full-time",
        skills: ["Figma", "UI/UX", "Wireframing", "Prototyping", "Design Systems"],
        description: "Join Razorpay's design team to craft high-conversion checkout flows, design systems, and responsive user experiences.",
        applicationUrl: "https://razorpay.com/jobs",
        postedAt: new Date(),
      },
      {
        source: "LinkedIn",
        sourceJobId: "cur-des-2",
        title: isFresher ? "Associate Product Designer" : "Product Designer",
        company: "Swiggy",
        location: loc,
        remoteType: "Hybrid",
        experienceMin: 0,
        experienceMax: isFresher ? 1 : 3,
        salaryMin: 900000,
        salaryMax: 1600000,
        employmentType: "Full-time",
        skills: ["Figma", "User Research", "User Flows", "Prototyping", "Interaction Design"],
        description: "Deliver intuitive food ordering and consumer experiences to tens of millions of active users daily.",
        applicationUrl: "https://www.linkedin.com/jobs",
        postedAt: new Date(),
      },
      {
        source: "Foundit",
        sourceJobId: "cur-des-3",
        title: isFresher ? "UI/UX Designer - Fresher / Graduate" : "UI/UX Designer",
        company: "CRED",
        location: loc,
        remoteType: "Hybrid",
        experienceMin: 0,
        experienceMax: isFresher ? 1 : 2,
        salaryMin: 1200000,
        salaryMax: 2000000,
        employmentType: "Full-time",
        skills: ["Figma", "Typography", "Visual Design", "UI/UX", "Micro-interactions"],
        description: "Design fluid, aesthetic, and award-winning financial interfaces that delight discerning members across India.",
        applicationUrl: "https://careers.cred.club",
        postedAt: new Date(),
      },
      {
        source: "LinkedIn",
        sourceJobId: "cur-des-4",
        title: isFresher ? "Entry-Level UX Designer" : "UX Designer",
        company: "Zomato",
        location: loc,
        remoteType: "On-site",
        experienceMin: 0,
        experienceMax: isFresher ? 1 : 3,
        salaryMin: 800000,
        salaryMax: 1400000,
        employmentType: "Full-time",
        skills: ["User Research", "Usability Testing", "Wireframing", "Figma", "Information Architecture"],
        description: "Work closely with product managers and engineers to conduct user interviews, usability testing, and wireframe prototypes.",
        applicationUrl: "https://www.linkedin.com/jobs",
        postedAt: new Date(),
      },
      {
        source: "Remotive",
        sourceJobId: "cur-des-5",
        title: isFresher ? "Junior Visual & Interaction Designer" : "Visual Designer",
        company: "Freshworks",
        location: loc,
        remoteType: "Remote",
        experienceMin: 0,
        experienceMax: isFresher ? 2 : 4,
        salaryMin: 700000,
        salaryMax: 1300000,
        employmentType: "Full-time",
        skills: ["Figma", "Adobe XD", "Photoshop", "Illustrator", "Design Systems"],
        description: "Collaborate with global teams to design sleek SaaS dashboards, marketing assets, and design component libraries.",
        applicationUrl: "https://remotive.com",
        postedAt: new Date(),
      },
      {
        source: "Foundit",
        sourceJobId: "cur-des-6",
        title: isFresher ? "UI/UX Design Trainee" : "UI/UX Specialist",
        company: "PhonePe",
        location: loc,
        remoteType: "Hybrid",
        experienceMin: 0,
        experienceMax: isFresher ? 1 : 3,
        salaryMin: 850000,
        salaryMax: 1500000,
        employmentType: "Full-time",
        skills: ["Figma", "User Flows", "Wireframing", "UI Design", "Mobile App Design"],
        description: "Contribute to payment and merchant UI flows supporting hundreds of millions of everyday UPI transactions.",
        applicationUrl: "https://www.phonepe.com/careers",
        postedAt: new Date(),
      },
    ];
  }

  // Developer default fallback
  return [
    {
      source: "Foundit",
      sourceJobId: "cur-dev-1",
      title: isFresher ? `Junior ${role}` : role,
      company: "Razorpay",
      location: loc,
      remoteType: "Hybrid",
      experienceMin: 0,
      experienceMax: isFresher ? 1 : 3,
      salaryMin: 800000,
      salaryMax: 1600000,
      employmentType: "Full-time",
      skills: criteria.skills?.slice(0, 5) || ["React", "JavaScript", "HTML", "CSS"],
      description: `Build and maintain modern web applications with cutting-edge web technologies. Great opportunity for ${isFresher ? "freshers" : "engineers"}.`,
      applicationUrl: "https://razorpay.com/jobs",
      postedAt: new Date(),
    },
    {
      source: "LinkedIn",
      sourceJobId: "cur-dev-2",
      title: isFresher ? `Associate ${role}` : role,
      company: "Swiggy",
      location: loc,
      remoteType: "Remote",
      experienceMin: 0,
      experienceMax: isFresher ? 1 : 3,
      salaryMin: 900000,
      salaryMax: 1800000,
      employmentType: "Full-time",
      skills: criteria.skills?.slice(0, 4) || ["React", "TypeScript", "Node.js"],
      description: "Deliver high-performance consumer applications to millions of active daily users.",
      applicationUrl: "https://www.linkedin.com/jobs",
      postedAt: new Date(),
    },
    {
      source: "Remotive",
      sourceJobId: "cur-dev-3",
      title: isFresher ? `Junior ${role} (Remote)` : `${role} (Remote)`,
      company: "CRED",
      location: loc,
      remoteType: "Remote",
      experienceMin: 0,
      experienceMax: isFresher ? 2 : 4,
      salaryMin: 1000000,
      salaryMax: 2000000,
      employmentType: "Full-time",
      skills: criteria.skills?.slice(0, 4) || ["TypeScript", "Next.js", "REST API"],
      description: "Develop fluid and aesthetic financial tech systems with exceptional attention to detail.",
      applicationUrl: "https://remotive.com",
      postedAt: new Date(),
    },
  ];
}
